# Development environment. This environment includes all the required
# packages for this repo including running the test suite.
name: coralviz
channels:
  - default
  - conda-forge
dependencies:
  - python==3.11.9
  - pip
  - pip:
    - pyleoclim